[package]
name = "astrafoto-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
reqwest = { version = "0.12.14", features = ["json"] }
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }